### ISSUE TITLE
Non weighted graph algorithms on weighted graphs

### ISSUE THREAD

**Issue by JanPalasek** [justcoding121/Advanced-Algorithms#28]
Hi, I need to perform Tarjan strongly components finding algorithm on a weighted directed graph. Is there any way to do that, except for manually trying to convert one graph to another? Thanks.

**Comment by justcoding121** [comment]
I don't think there is a way to do this without converting. I will try to update the graph algorthims to be generic enough to accept all types of graphs.

**Comment by justcoding121** [comment]
Updated beta to accept generic a graph interface. If you pass a Weighted DiGraph, it will use OutEdges to run the algorithm.
