### ISSUE TITLE
Graph Clone

### ISSUE THREAD

**Issue by JanPalasek** [justcoding121/Advanced-Algorithms#29]
Hi,

would it be possible for Clone() method on graphs to be public? Is there any reason why it's not at the moment?
For example I want to build one part of the graph (because it's static for my problem), but later I'd like to add some edges. I don't want to modify the static part of the graph because I will need it once more. Now I'm forced to Clone it myself and I don't even know how to do it, because I don't see any way of enumerating the vertices atm (only enumerating the vertex values).

**Comment by justcoding121** [comment]
I've made clone methods public in the latest beta.
