### ISSUE TITLE
FloydWarshallShortestPathOperators() (and others) not found 

### ISSUE THREAD

**Issue by AlzyPalzy** [justcoding121/Advanced-Algorithms#31]
Firstly, massive and heartfelt thanks for this great selection of algorithms I need to write my project. Been trying them out - saved me weeks of coding and testing.

For this (and the Dijkstra and possibly others) VS can't seem to locate the classes inherited from the abstract IShortestPathOperators in any of the using directives. I've tried quite a few. Not a massive problem as I copied the FloydWarshallShortestPathOperators class into my project from your online source code and all works well, but I figure you intended that they should be automatically available somewhere.

Anyway, thanks again, these are fantastic!

**Comment by justcoding121** [comment]
It was intended that the concrete implementation should provided by the developer to accommodate the datatypes/data structure used for distance. You could copy the one used in the unit test project if that matches your data type.
