### ISSUE TITLE
Bentley-Ottman algorithm throws exception with certain input

### ISSUE THREAD

**Issue by kiraventom** [justcoding121/Advanced-Algorithms#33]
Bentley-Ottman algorithm throws NullReferenceException with certain input.
Example input:
Line 1: 100, 0; 150, 130
Line 2: 20, 80; 80, 70
Line 3: 80, 70; 50, 100

**Comment by justcoding121** [comment]
I've fixed this and published Advanced.Algorithms.0.0.463-beta.nupkg on to NuGet.
