### ISSUE TITLE
HopcroftKarpMatching Bug

### ISSUE THREAD

**Issue by kazimierz-256** [justcoding121/advanced-algorithms#34]
Given a simple fully connected bipartite graph K_{3,3} the maximum matching algorithm crashes with an error:
assuming U={A, B, C} and V={D, E, F}
the exception is raised in the following line:

https://github.com/justcoding121/Advanced-Algorithms/blob/0e1b90aaf322104ec9bdf7e5b4ab55a39e920aed/src/Advanced.Algorithms/Graph/Matching/HopcroftKarp.cs#L57

> **System.ArgumentException:** 'An item with the same key has already been added. Key: E'

Since _rightMatch_ dictionary already contains a mapping between E and A the algorithm cannot add a mapping between E and C on top of it

**Comment by justcoding121** [comment]
Will take a look when I get a chance, been busy lately. Meanwhile, feel free to shoot a PR if you find a fix.

**Comment by justcoding121** [comment]
Fixed.
