### ISSUE TITLE
Bipartite Matching Ford-Fulkerson Bug

### ISSUE THREAD

**Issue by kazimierz-256** [justcoding121/Advanced-Algorithms#35]
The following graph is considered as not bipartite by the algorithm (which in reality is):
(0) -- (2)
(1) -- (3)

as in MColorer appears to be unable to color the disconnected graph using 2 colors.

https://github.com/justcoding121/Advanced-Algorithms/blob/0e1b90aaf322104ec9bdf7e5b4ab55a39e920aed/tests/Advanced.Algorithms.Tests/Graph/Matching/BiPartiteMatching_Tests.cs#L40

**Comment by justcoding121** [comment]
Thanks for reporting this Bug. I've identified the issue and will make a new release soon with the fix.
