### ISSUE TITLE
I imagine you probably meant to test the AdjacencyList here rather than AdjacencyMatrix

### ISSUE THREAD

**Issue by TimeJunkie** [justcoding121/Advanced-Algorithms#37]
https://github.com/justcoding121/advanced-algorithms/blob/6ce425ed0fa63afef9d9fb97e0cbdae7a06a0d33/tests/Advanced.Algorithms.Tests/Graph/ShortestPath/Dijikstras_Tests.cs#L12

**Comment by justcoding121** [comment]
Yup. Fixed. Thanks
