### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by lucasmontec** [justcoding121/Advanced-Algorithms#38]
Thanks for this library! It is the best I have found on C# for this. I'd suggest you add some C# documentation on your main calls. Although comments usually are a bad practice, for libraries they really help to understand the calls.
For example, by reading the code I could understand what the combination class does, but by reading the method name itself, I couldn't. It would be nice to provide at least a simple example of input/output. Nothing more.

**Comment by justcoding121** [comment]
Thank you for the suggestion.

For example, you can check the test methods. 
Each algorithm has simple test cases.

Combination tests are below.
https://github.com/justcoding121/Advanced-Algorithms/blob/develop/tests/Advanced.Algorithms.Tests/Combinatorics/Combination_Tests.cs

https://justcoding121.github.io/advanced-algorithms/docs/api/Advanced.Algorithms.Combinatorics.Combination.html
