### ISSUE TITLE
Dijikstra TracePath bug

### ISSUE THREAD

**Issue by OlegYudovich** [justcoding121/Advanced-Algorithms#5]
tracePath method implementation not working for all Nullible types. While loop:

while (!currentV.Equals(default(T)) && !parentMap[currentV].Equals(default(T)))

Will throw null reference exception on null.equals(null)

**Comment by justcoding121** [comment]
https://www.nuget.org/packages/Advanced.Algorithms/0.0.140-beta

Please try latest release.

**Comment by justcoding121** [comment]
Updated

**Comment by justcoding121** [comment]
Plz one if not fixed. Thx
